name: Release Deployment

on:
  push:
    tags:
      - 'v*'

jobs:
  release-deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract latest tag name
        id: tag
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Delete previous 'latest' release
        if: ${{ !contains(env.TAG_NAME, 'beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/latest" \
            | jq -r '.id')

          if [ "$RELEASE_ID" != "null" ]; then
            curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID"
            echo "Deleted 'latest' release."
          else
            echo "Could not delete 'latest' release."
          fi

      - name: Delete previous 'latest' tag
        if: ${{ !contains(env.TAG_NAME, 'beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_SHA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/git/ref/tags/latest" \
            | jq -r '.object.sha')

          if [ "$TAG_SHA" != "null" ]; then
            curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/git/refs/tags/latest"
            echo "Deleted 'latest' tag."
          else
            echo "Could not delete 'latest' tag."
          fi

      - name: Create new 'latest' tag
        if: ${{ !contains(env.TAG_NAME, 'beta') }}
        run: |
          git tag latest
          git push origin latest

      - name: Create new 'latest' release
        if: ${{ !contains(env.TAG_NAME, 'beta') }}
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_BODY=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.TAG_NAME }}" \
          | jq -r '.body')

          JSON_PAYLOAD=$(jq -n \
          --arg body "$RELEASE_BODY" \
          '{
            "tag_name": "latest",
            "name": "latest",
            "body": $body,
          }')

          curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d "$JSON_PAYLOAD"